#Keto calorie program

proteins = {
    'chicken':{'serv': 4, 'cal': 130, 'fat(g)': 3, 'pro(g)': 25, 'carb(g)': 0, 'sod(mg)': 45, 'chol(mg)': 60},#oz
    'egg':{'serv': 1, 'cal': 70, 'fat(g)': 45, 'pro(g)': 24, 'carb(g)': 0.5, 'sod(mg)': 70, 'chol(mg)': 185},#egg,
    'bacon(ls)':{'serv': 2, 'cal': 80, 'fat(g)': 54, 'pro(g)':6, 'carb(g)':0, 'sod(mg)':160, 'chol(mg)':15},#slices
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'protein':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

fats = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'fat':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

carbs = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'carb':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

veggies = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'veg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

fruits = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'fruit':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

condiments = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'cond':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

flavors = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'flavor':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

drinks = {
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'egg':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
    'drink':{'serv': x, 'cal': x, 'fat(g)': x, 'pro(g)':x, 'carb(g)':x, 'sod(mg)':x, 'chol(mg)':x},
}

print(proteins[values])